.\" Copyright (c) 2019 Greg White <gkwhite@gmail.com>.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd January 6, 2019
.Dt GZERO 4
.Os
.Sh NAME
.Nm gzero
.Nd the zero disk/block device
.Sh DESCRIPTION
The
.Nm
device is provider in the 
.Xr GEOM 4
modular disk I/O requestion transformation framework.  It simulates
a 1 Exabyte write-only disk where all blocks read are filled with the byte 0x00.
It differs from 
.Xr zero 4 ,
which is a regular character device and has an infinite length.  The /dev/gzero device is created by loading the geom_zero kernel module with either the command:
.Pp
.Dl # kldload geom_zero
or
.Dl # geom load zero
.Pp
The /dev/gzero device is removed by unloading the geom_zero kernel module with either the command
.Pp
.Dl # kldunload geom_zero
or
.Dl # geom unload zero
.Pp
Once loaded, information about the gzero device can be found with the following command:
.Pp
.Dl # geom zero list
.Dl Geom name: gzero
.Dl Providers:
.Dl 1. Name: gzero
.Dl "   Mediasize: 1152921504606846976 (1.0E)"
.Dl "   Sectorsize: 512"
.Dl "   Mode: r0w0e0"
.Pp
You can set the fill byte of the gzero device (in this case to 42) using the following sysctl:
.Pp
.Dl # sysctl kern.geom.zero.clear=42
.Pp
It can be used as a simple benchmark of the speed of a disk or subsystem, 
where compression of the data does not affect the results (clearly, blocks from 
/dev/gzero will compress exceptionally well.)  Example of a benchmarks that might 
use /dev/gzero is comparing the speed of two disk encryption algorithms or
comparing a hardware versus software implementation of a single encryption algorithms.
.Sh FILES
.Bl -tag -width /dev/gzero
.It Pa /dev/gzero
.El
.Sh SEE ALSO
.Xr GEOM 4 ,
.Xr zero 4 ,
.Xr geom 8 ,
.Xr sysctl 8
.Rs
.%B "The FreeBSD Handbook"
.%T "18.3.3. Creating a Mirror with an Existing Drive"
.%U https://www.freebsd.org/doc/handbook/geom-mirror.html#geom-mirror-existing-drive
.Re
.Sh HISTORY
A
.Nm 
device first appeared in 
.Fx 6
.Sh AUTHORS
.An -nosplit
The 
.Nm
device was written by
.An Pawel Jakub Dawidek <pjd@FreeBSD.org> .
The
.Nm
manual page was written by
.An Greg White Aq Mt gkwhite@gmail.com .
